EMAIL = 'semenkulagin14666@gmail.com'
PASSWORD = '123456'
LOGIN_PAGE_LINK = 'https://stellarburgers.nomoreparties.site/login'
ACCOUNT_PAGE_LINK = 'https://stellarburgers.nomoreparties.site/account/profile'
NAME = 'Семён'
